name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2' 

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: flutter format --set-exit-if-changed .

      - name: Run analyzer (static analysis for errors/warnings)
        run: flutter analyze

      - name: Run tests
        run: flutter test
